<h2>Numpy</h2> 


Powerful Library in python that provides support for working with arrays

In [22]:
import numpy as np

# Creation of array 1D
arr = np.array([25,41,63,66,85,74])
arr

array([25, 41, 63, 66, 85, 74])

In [23]:
type(arr)

# ndarray --> n dimensional array

numpy.ndarray

In [24]:
arr.size # total items in array is printed

6

In [25]:
len(arr) # also be used to find total items in array is printed

6

In [26]:
arr.ndim # to ccheck the dimension of array

1

In [27]:
arr = np.array([25,41,63,66,85,74])
arr

array([25, 41, 63, 66, 85, 74])

In [28]:
arr.dtype # to check the datatype

dtype('int64')

In [29]:
# np.__version__

In [30]:
arr = np.array([25,41,63,66,85,74])
arr

array([25, 41, 63, 66, 85, 74])

In [31]:
# Indexing is also there positive & Negative
arr[-1] = 500
arr


array([ 25,  41,  63,  66,  85, 500])

In [32]:
# ([ 25,  41,  63,  66,  85, 500])
arr+2 # in each and every item will be added by 2

array([ 27,  43,  65,  68,  87, 502])

<h3>2D ARRAY</h3>

In [36]:
# 2D = [1D,1D,1D....]

ls = [[1,2,3],
      [4,5,6],
      [7,8,9]]

arr = np.array(ls)
arr.ndim
arr.shape # (3, 3)  3row , 3column

(3, 3)

In [44]:
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr[-2:,-2:]

array([[5, 6],
       [8, 9]])

In [131]:
arr = np.random.randint(1,200,500) # to generate number
print(arr)

[ 76 171 112 120 104  99  39  35 104  50 104  31  26 119 109 157 154  36
 159 159 179 166   6 135 151 102 146 140 134  76  37 190 175 104  10 196
 198 100  77 153 150 163  96  74  96 177   4 180 145  89  51  43  54  32
 105  89 128  19 100 163 159 132 134 185 135  85 102  58   7  26 146 142
 167  36 185 189  61 187 107  39 131  49 190 101  33  53  33  28  41 162
  53  32 115 104  35 196 125 199 145 125  60  12 165  36 140 134 138  31
 196  71 107 141  87  45 187 174  85 185 196 195 167  32 178 101  15  19
  36 193 121  22 197  75  81 124 141 143 180  42 119 162 129 139 134  40
  20 173  33  38 165 114  50  46  89 144  14  10  77   4  57 141  82  67
  12 187  68  86 166  23  12 164  63 125   4 190 136  66  47  92 164 178
  80  51 161 165  43 168   4  18 198 168 149 111   3  48  15  50 148  33
   7 164 168   3 120 186 171 120 117  18 127  71  82  55 141 108  37 165
 186  81  97   3  72  27  40 144  99  58  94 194 129  32 182 153 186 140
 128   1  54 158  35  86  95  96 105  92  44 184 14

In [132]:
len(arr[arr<=100]) # to calculate the number of items less than equal to 100 

251

In [210]:
arr2 = np.random.randint(1,200,(10,5)) # generate 2d array of 10 row and 5 column
arr2

array([[ 22,   1, 156,  25,  59],
       [196, 180, 111, 129,  14],
       [ 11,  83, 191, 177,  46],
       [ 86,  81, 137,  26, 161],
       [  8,  96,  52,  66,  19],
       [177,  42, 176,   6, 107],
       [126,  27,  32, 171, 190],
       [114,  75,  71,  64, 182],
       [195, 151, 105, 171, 131],
       [ 80, 175,  54, 145, 130]], dtype=int32)

In [212]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [213]:
arr = np.zeros((10,5)) # 10 row 5 column with item = 0
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [216]:
arr = np.ones((10,5)) # 10 row 5 column with item = 1
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [220]:
ls = [0,1,2,3,4,5,6,7,8,9]
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [222]:
ls  = list(range(10)) # creates list from range 0-10
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [226]:
np.arange(10) # creates array from range 0-10
# creates always 1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [228]:
arr = np.arange(60)
arr # 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [235]:
# 2D , 60
# 10,6
arr = arr.reshape(6,10) # 1D --> 2D
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [237]:
arr.reshape(3,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59]])