In [133]:
import numpy as np

arr3 = np.random.randint(1,200,(3,5,3))
# arr3.ndim
arr3.shape # (table, row, column)

(3, 5, 3)

In [134]:
arr3.ndim # arr3 is 3 dimensional array
arr3

array([[[187,  45, 129],
        [192,  33, 187],
        [128,  55,  57],
        [193, 171, 122],
        [  8, 171,  52]],

       [[ 84, 114, 157],
        [ 36,  94, 179],
        [116,  90, 164],
        [180, 110, 131],
        [ 25, 154,  50]],

       [[ 88,  13, 165],
        [116, 156,  29],
        [187,   7, 124],
        [178, 159, 166],
        [ 73,  12,  65]]], dtype=int32)

In [135]:
arr3[-3:,-5,-3:]


array([[187,  45, 129],
       [ 84, 114, 157],
       [ 88,  13, 165]], dtype=int32)

In [136]:
arr = np.array([1,2,4,3])

In [137]:
np.max(arr)

np.int64(4)

In [138]:
np.min(arr)

np.int64(1)

In [139]:
np.sum(arr)

np.int64(10)

In [140]:
np.argmin(arr) # returns the index position of the minimum item

np.int64(0)

In [141]:
np.argmax(arr) # returns the index position of the maximum item

np.int64(2)

In [142]:
arr.sort() # Ascending order
arr

array([1, 2, 3, 4])

In [143]:
arr[::-1] # Descending order

array([4, 3, 2, 1])

In [144]:
arr.sort()

<h2>Pandas :</h2>

Pandas is also a Python is a open source library/module.

Data analysis , manipulation , transform , cleaning , sorting , searching , preprocessing , filtering

Pandas is used for accessing or read the data from the different formats.

import pandas

In [145]:
import pandas as pd
import numpy as np

In [146]:
# What is dataframe 
# How we can create dataframe  , array , list , dictionary
# For creation of the dataframe we have to create a dictionary

dt = {"Name":['Ritu','Taniya','abhishek','tanmay','mayank'],
     "Branch":['it','cse','it','ece','cse'],
     "Class":[2,3,4,1,2], 
     "City":['jaipur','agra','vridavan','mathura','gokul']}

In [147]:
df = pd.DataFrame(dt)
df

Name Branch  Class      City
0      Ritu     it      2    jaipur
1    Taniya    cse      3      agra
2  abhishek     it      4  vridavan
3    tanmay    ece      1   mathura
4    mayank    cse      2     gokul

In [148]:
# key --> column name
# value --> column entries
# 0,1,2,3,4 are the index


In [149]:
type(df)

pandas.core.frame.DataFrame

In [150]:
# Series is like a single column
df['Name']

0        Ritu
1      Taniya
2    abhishek
3      tanmay
4      mayank
Name: Name, dtype: object

In [151]:
type(df['Name'])

pandas.core.series.Series

In [152]:
df

Name Branch  Class      City
0      Ritu     it      2    jaipur
1    Taniya    cse      3      agra
2  abhishek     it      4  vridavan
3    tanmay    ece      1   mathura
4    mayank    cse      2     gokul

In [153]:
df.dtypes

Name      object
Branch    object
Class      int64
City      object
dtype: object

In [154]:
df.shape
# 5 --> rows
# 4 --> columns

(5, 4)

In [155]:
df.Name # df['Name']

0        Ritu
1      Taniya
2    abhishek
3      tanmay
4      mayank
Name: Name, dtype: object

In [156]:
df[['Name','Branch']]

Name Branch
0      Ritu     it
1    Taniya    cse
2  abhishek     it
3    tanmay    ece
4    mayank    cse

In [157]:
df[['Branch','Class']]

Branch  Class
0     it      2
1    cse      3
2     it      4
3    ece      1
4    cse      2

In [158]:
df[1:2]

Name Branch  Class  City
1  Taniya    cse      3  agra

In [159]:
df[1:3][['Name','Branch']]

Name Branch
1    Taniya    cse
2  abhishek     it

LOC --> stoping point is included

iLOC -->  stoping point is not included

In [160]:
df.loc[3:4,['Branch','Class','City']]

Branch  Class     City
3    ece      1  mathura
4    cse      2    gokul

In [161]:
df.iloc[3:,1:]

Branch  Class     City
3    ece      1  mathura
4    cse      2    gokul