<h2>Numpy Library :-</h2>

NumPy is a fundamental library for scientific computing in Python, widely used for its powerful features and capabilities. 

NumPy provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

NumPy allows to perform arithmetic operations on arrays of different shapes and sizes without needing to explicitly reshape them. 
This makes code simpler and more intuitive.

Many other scientific computing and data analysis libraries, such as SciPy, Pandas, Matplotlib, and Scikit-Learn, are built on top of NumPy arrays, 
ensuring compatibility and seamless integration.

NumPy arrays consume less memory.

NumPy includes functions for linear algebra operations, Fourier transforms, and random number generation, which are essential for many scientific and engineering applications.

In [45]:
# To Download numpy library --> pip install numpy (write in command prompt)
# Import the numpy library as np

import numpy as np

<h4>1-Dimension Array :-</h4>

In [46]:
# Creation of array 1D
arr = np.array([25,41,63,66,85,74])
arr

array([25, 41, 63, 66, 85, 74])

In [47]:
type(arr) # ndarray --> n dimensional array

# type() function is used to determine the type of an object.

numpy.ndarray

In [48]:
arr.dtype
# The dtype attribute of a NumPy array is used to determine the type of elements stored in the array.

dtype('int64')

In [49]:
arr.size #  The size attribute of an array returns the total number of elements in the array

6

In [50]:
len(arr) # The len() function is a built-in Python function used to get the number of items in a container

6

In [51]:
arr.ndim # The ndim attribute is used to determine the number of dimensions of an array. 

1

<h5>Indexing in 1-D Array:-</h5>

Indexing in a 1D NumPy array is similar to indexing in standard Python lists. 

In [52]:
# Creating a 1D NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Accessing elements
print(arr[0])  # Output: 10
print(arr[2])  # Output: 30

10
30


In [53]:
# Modifying elements
arr[1] = 25
print(arr)  # Output: [10 25 30 40 50]

[10 25 30 40 50]


In [54]:
# Slicing elements
print(arr[1:4])  # Output: [25 30 40]
print(arr[:3])   # Output: [10 25 30]
print(arr[::2])  # Output: [10 30 50]
print(arr[-3:])  # Output: [30 40 50]  (slicing with negative index)

[25 30 40]
[10 25 30]
[10 30 50]
[30 40 50]


In [55]:
# The numpy.random.randint() function in NumPy is used to generate random integers within a specified range.
arr = np.random.randint(1,200,500)
print(arr)

[ 81  82  31 193  62  53  40 196  82  84  49 120  57  60  58  32  44  35
 176  13  25 156 157   6  18  62 180 163  21 170  87 109 104  82  49 172
 113  11 122  43  24   8  10 144   7 146  61 156 101 127  98 132 170  99
  10  82  59  16 160  53 108  94  53  11  87 192 181 148 141  52  55 158
  53 135 194  76  14 121 174  65 185   4  78  25  28 145 134 173   5  14
 164 135  27  40  35 100  88  25 100  54 132 199  79  49  17 179 162  96
  97  76 159 113  10 156 168 137  36  39 194 183 133 125  39 173 147  92
 119 123 141 164  63 167  82  87  97 162  63  48 155 102 124  17 161  90
 193 146 105  20  22 157  98 127  35  60  93  76 147  33  96 142 123  18
  63   1 149  75  10 177 180 162 137  91 175   8  54 167 197  42 172  64
 159  81 152 197  70 163 134 197 181  29  44  80 172   6 130  55  29 151
   7  20  54 171  92 163 155 111 152 156   6 193 104 101  35 167 191  13
   1  34  30 171 140  88  73  93  40 106  55 162 180  94  14 102   6 115
  90 129 193 136 184   8 166  84 178   9 166  99 12

<h4>2-Dimension Array :-</h4>

2D arrays (also known as matrices) in NumPy is a common task in scientific computing and data analysis. 

NumPy provides a range of functionalities to create, manipulate, and perform operations on 2D arrays.

In [56]:
# Creating a 2D NumPy array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [57]:
# Accessing elements
print("Element at (0, 0):", arr2d[0, 0])  # Output: 1
print("Element at (1, 2):", arr2d[1, 2])  # Output: 6

Element at (0, 0): 1
Element at (1, 2): 6


In [58]:
# Modifying elements
arr2d[1, 2] = 10
print("Modified 2D Array:")
print(arr2d)

Modified 2D Array:
[[ 1  2  3]
 [ 4  5 10]
 [ 7  8  9]]


In [59]:
# Slicing rows
print("First two rows:")
print(arr2d[:2])

First two rows:
[[ 1  2  3]
 [ 4  5 10]]


In [60]:
# Slicing columns
print("First two columns:")
print(arr2d[:, :2])

First two columns:
[[1 2]
 [4 5]
 [7 8]]


In [61]:
# Transposing the array
print("Transposed Array:")
print(arr2d.T)

Transposed Array:
[[ 1  4  7]
 [ 2  5  8]
 [ 3 10  9]]


In [62]:
# Summing all elements
print("Sum of all elements:", np.sum(arr2d))

Sum of all elements: 49


In [63]:
# Element-wise operations
print("Element-wise multiplication:")
print(arr2d * 2)

Element-wise multiplication:
[[ 2  4  6]
 [ 8 10 20]
 [14 16 18]]


In [64]:
# Matrix multiplication
arr2d_2 = np.array([[1, 2], [3, 4], [5, 6]])
print(np.dot(arr2d, arr2d_2))

[[ 22  28]
 [ 69  88]
 [ 76 100]]


<h4>3-Dimension Array :-</h4>

3-dimensional (3D) arrays in NumPy involves similar concepts to working with 2D arrays but adds an additional dimension for more complex data structures.

In [65]:
arr3 = np.random.randint(1,200,(3,5,3))

In [66]:
# The shape attribute of an array provides a tuple representing the dimensions of the array.

arr3.shape # (table, row, column)

(3, 5, 3)

In [67]:
# Creating a 3D NumPy array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                  [[7, 8, 9], [10, 11, 12]], 
                  [[13, 14, 15], [16, 17, 18]]])

# Accessing specific elements
print(arr3d[0, 0, 0])  # Output: 1
print(arr3d[1, 1, 2])  # Output: 12
print(arr3d[2, 1, 1])  # Output: 17

1
12
17


<h3>Numpy Functions :-</h3>

In [68]:
# The zeros() function in NumPy is used to create an array filled with zeros.

arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
arr = np.zeros((10,5)) # 10 row 5 column with item = 0
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [70]:
# The ones() function in NumPy is used to create an array filled with ones.

arr = np.ones((10,5)) # 10 row 5 column with item = 1
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [71]:
# The arange() function in NumPy is used to create arrays with evenly spaced values within a specified range.
# numpy.arange(start, stop, step)

np.arange(10) # creates array from range 0-10
# creates always 1D array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr = np.arange(60)
arr # 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [73]:
# The reshape() function in NumPy is used to change the shape of an existing array without modifying its data.
arr = arr.reshape(6,10) # 1D --> 2D
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [74]:
arr = np.array([1,2,4,3])
np.max(arr) # used to find the maximum value in an array.

np.int64(4)

In [75]:
np.min(arr) # used to find the minimum value in an array.

np.int64(1)

In [76]:
np.sum(arr) # used to compute the sum of array elements over a specified axis or the entire array.

np.int64(10)

In [77]:
np.argmin(arr) # returns the index position of the minimum item

np.int64(0)

In [78]:
np.argmax(arr) # returns the index position of the maximum item

np.int64(2)

In [79]:
# used to sort elements of an array along a specified axis. It returns a sorted copy of the array.
arr.sort() # Ascending order
arr

array([1, 2, 3, 4])

In [80]:
arr[::-1] # Descending order

array([4, 3, 2, 1])